func handleRequest(w http.ResponseWriter, r *http.Request) {
    // ... other code ...
    defer r.Body.Close() // This line is crucial for proper resource management
    // ... rest of the request handling ...
}